import type { Destination } from '@/types'

export const destinations: Destination[] = [
  {
    id: 'dominican-republic',
    slug: 'dominican-republic',
    name: 'Dominican Republic',
    type: 'country',
    continent: 'caribbean',
    flagEmoji: '🇩🇴',
    currency: {
      code: 'DOP',
      name: 'Dominican Peso',
      symbol: 'RD$',
      exchangeRateToUsd: 57.5,
      budgetPerDay: {
        budget: 40,
        midRange: 80,
        luxury: 200,
      },
    },
    languages: ['Spanish'],
    timezone: 'AST (UTC-4)',
    visaInfo: 'Visa-free for most nationalities up to 30 days',
    bestTimeToVisit: 'December to April',
    seo: {
      metaTitle: 'Dominican Republic Travel Guide 2026 | Lowcost Traveling',
      metaDescription:
        'Complete Dominican Republic travel guide. Best beaches, budget tips, and practical info for 2026.',
      keywords: ['dominican republic', 'caribbean', 'punta cana', 'budget travel'],
    },
  },
  {
    id: 'vatican',
    slug: 'vatican',
    name: 'Vatican City',
    type: 'microstate',
    continent: 'europe',
    flagEmoji: '🇻🇦',
    currency: {
      code: 'EUR',
      name: 'Euro',
      symbol: '€',
      exchangeRateToUsd: 1.08,
      budgetPerDay: {
        budget: 50,
        midRange: 100,
        luxury: 250,
      },
    },
    languages: ['Italian', 'Latin'],
    timezone: 'CET (UTC+1)',
    visaInfo: 'No border control, accessed through Rome',
    bestTimeToVisit: 'April to June, September to October',
    seo: {
      metaTitle: 'Vatican City Travel Guide 2026 | Lowcost Traveling',
      metaDescription:
        'Everything you need to know about visiting Vatican City. Skip the lines and see the best of the smallest country.',
      keywords: ['vatican', 'rome', 'sistine chapel', 'italy travel'],
    },
  },
  {
    id: 'thailand',
    slug: 'thailand',
    name: 'Thailand',
    type: 'country',
    continent: 'asia',
    flagEmoji: '🇹🇭',
    currency: {
      code: 'THB',
      name: 'Thai Baht',
      symbol: '฿',
      exchangeRateToUsd: 35.5,
      budgetPerDay: {
        budget: 30,
        midRange: 60,
        luxury: 150,
      },
    },
    languages: ['Thai', 'English'],
    timezone: 'ICT (UTC+7)',
    visaInfo: 'Visa-free for most nationalities up to 30-60 days',
    bestTimeToVisit: 'November to February',
    seo: {
      metaTitle: 'Thailand Travel Guide 2026 | Lowcost Traveling',
      metaDescription:
        'Complete Thailand travel guide. From Bangkok to the islands, budget tips and insider advice for 2026.',
      keywords: ['thailand', 'bangkok', 'thai islands', 'southeast asia', 'budget travel'],
    },
  },
  {
    id: 'portugal',
    slug: 'portugal',
    name: 'Portugal',
    type: 'country',
    continent: 'europe',
    flagEmoji: '🇵🇹',
    currency: {
      code: 'EUR',
      name: 'Euro',
      symbol: '€',
      exchangeRateToUsd: 1.08,
      budgetPerDay: {
        budget: 45,
        midRange: 90,
        luxury: 200,
      },
    },
    languages: ['Portuguese'],
    timezone: 'WET (UTC+0)',
    visaInfo: 'Schengen area - 90 days visa-free for most nationalities',
    bestTimeToVisit: 'March to May, September to October',
    seo: {
      metaTitle: 'Portugal Travel Guide 2026 | Lowcost Traveling',
      metaDescription:
        'Complete Portugal travel guide. Lisbon, Porto, Algarve beaches, and budget tips for 2026.',
      keywords: ['portugal', 'lisbon', 'porto', 'algarve', 'europe travel'],
    },
  },
  {
    id: 'morocco',
    slug: 'morocco',
    name: 'Morocco',
    type: 'country',
    continent: 'africa',
    flagEmoji: '🇲🇦',
    currency: {
      code: 'MAD',
      name: 'Moroccan Dirham',
      symbol: 'د.م.',
      exchangeRateToUsd: 10.1,
      budgetPerDay: {
        budget: 35,
        midRange: 70,
        luxury: 180,
      },
    },
    languages: ['Arabic', 'French', 'Berber'],
    timezone: 'WET (UTC+0/+1)',
    visaInfo: 'Visa-free for most nationalities up to 90 days',
    bestTimeToVisit: 'March to May, September to November',
    seo: {
      metaTitle: 'Morocco Travel Guide 2026 | Lowcost Traveling',
      metaDescription:
        'Complete Morocco travel guide. Marrakech, Sahara desert, and budget tips for 2026.',
      keywords: ['morocco', 'marrakech', 'sahara', 'fes', 'africa travel'],
    },
  },
  {
    id: 'bali',
    slug: 'bali',
    name: 'Bali',
    type: 'region',
    parentId: 'indonesia',
    continent: 'asia',
    flagEmoji: '🇮🇩',
    currency: {
      code: 'IDR',
      name: 'Indonesian Rupiah',
      symbol: 'Rp',
      exchangeRateToUsd: 15700,
      budgetPerDay: {
        budget: 35,
        midRange: 70,
        luxury: 200,
      },
    },
    languages: ['Indonesian', 'Balinese', 'English'],
    timezone: 'WITA (UTC+8)',
    visaInfo: 'Visa on arrival for most nationalities (30 days)',
    bestTimeToVisit: 'April to October',
    seo: {
      metaTitle: 'Bali Travel Guide 2026 | Lowcost Traveling',
      metaDescription:
        'Complete Bali travel guide. Beaches, temples, rice terraces, and budget tips for 2026.',
      keywords: ['bali', 'indonesia', 'ubud', 'seminyak', 'southeast asia'],
    },
  },
]
