/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as DestinationsContinentRouteImport } from './routes/destinations.$continent'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsContinentRoute = DestinationsContinentRouteImport.update({
  id: '/destinations/$continent',
  path: '/destinations/$continent',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/destinations/$continent': typeof DestinationsContinentRoute
  '/articles/': typeof ArticlesIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/destinations/$continent': typeof DestinationsContinentRoute
  '/articles': typeof ArticlesIndexRoute
  '/destinations': typeof DestinationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/destinations/$continent': typeof DestinationsContinentRoute
  '/articles/': typeof ArticlesIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles/$slug'
    | '/destinations/$continent'
    | '/articles/'
    | '/destinations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles/$slug'
    | '/destinations/$continent'
    | '/articles'
    | '/destinations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles/$slug'
    | '/destinations/$continent'
    | '/articles/'
    | '/destinations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  DestinationsContinentRoute: typeof DestinationsContinentRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$continent': {
      id: '/destinations/$continent'
      path: '/destinations/$continent'
      fullPath: '/destinations/$continent'
      preLoaderRoute: typeof DestinationsContinentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  DestinationsContinentRoute: DestinationsContinentRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
