/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as EbookDownloadRouteImport } from './routes/ebook.download'
import { Route as DestinationsContinentRouteImport } from './routes/destinations.$continent'
import { Route as BookSuccessRouteImport } from './routes/book.success'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as DestinationsGuideSlugRouteImport } from './routes/destinations.guide.$slug'

const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookDownloadRoute = EbookDownloadRouteImport.update({
  id: '/ebook/download',
  path: '/ebook/download',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsContinentRoute = DestinationsContinentRouteImport.update({
  id: '/destinations/$continent',
  path: '/destinations/$continent',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSuccessRoute = BookSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsGuideSlugRoute = DestinationsGuideSlugRouteImport.update({
  id: '/destinations/guide/$slug',
  path: '/destinations/guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/book/success': typeof BookSuccessRoute
  '/destinations/$continent': typeof DestinationsContinentRoute
  '/ebook/download': typeof EbookDownloadRoute
  '/articles/': typeof ArticlesIndexRoute
  '/book/': typeof BookIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/guide/$slug': typeof DestinationsGuideSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/book/success': typeof BookSuccessRoute
  '/destinations/$continent': typeof DestinationsContinentRoute
  '/ebook/download': typeof EbookDownloadRoute
  '/articles': typeof ArticlesIndexRoute
  '/book': typeof BookIndexRoute
  '/destinations': typeof DestinationsIndexRoute
  '/destinations/guide/$slug': typeof DestinationsGuideSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/book/success': typeof BookSuccessRoute
  '/destinations/$continent': typeof DestinationsContinentRoute
  '/ebook/download': typeof EbookDownloadRoute
  '/articles/': typeof ArticlesIndexRoute
  '/book/': typeof BookIndexRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/destinations/guide/$slug': typeof DestinationsGuideSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/articles/$slug'
    | '/book/success'
    | '/destinations/$continent'
    | '/ebook/download'
    | '/articles/'
    | '/book/'
    | '/destinations/'
    | '/destinations/guide/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles/$slug'
    | '/book/success'
    | '/destinations/$continent'
    | '/ebook/download'
    | '/articles'
    | '/book'
    | '/destinations'
    | '/destinations/guide/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/articles/$slug'
    | '/book/success'
    | '/destinations/$continent'
    | '/ebook/download'
    | '/articles/'
    | '/book/'
    | '/destinations/'
    | '/destinations/guide/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRouteWithChildren
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  DestinationsContinentRoute: typeof DestinationsContinentRoute
  EbookDownloadRoute: typeof EbookDownloadRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  DestinationsGuideSlugRoute: typeof DestinationsGuideSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof BookRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook/download': {
      id: '/ebook/download'
      path: '/ebook/download'
      fullPath: '/ebook/download'
      preLoaderRoute: typeof EbookDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$continent': {
      id: '/destinations/$continent'
      path: '/destinations/$continent'
      fullPath: '/destinations/$continent'
      preLoaderRoute: typeof DestinationsContinentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/success': {
      id: '/book/success'
      path: '/success'
      fullPath: '/book/success'
      preLoaderRoute: typeof BookSuccessRouteImport
      parentRoute: typeof BookRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/guide/$slug': {
      id: '/destinations/guide/$slug'
      path: '/destinations/guide/$slug'
      fullPath: '/destinations/guide/$slug'
      preLoaderRoute: typeof DestinationsGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookRouteChildren {
  BookSuccessRoute: typeof BookSuccessRoute
  BookIndexRoute: typeof BookIndexRoute
}

const BookRouteChildren: BookRouteChildren = {
  BookSuccessRoute: BookSuccessRoute,
  BookIndexRoute: BookIndexRoute,
}

const BookRouteWithChildren = BookRoute._addFileChildren(BookRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRouteWithChildren,
  ArticlesSlugRoute: ArticlesSlugRoute,
  DestinationsContinentRoute: DestinationsContinentRoute,
  EbookDownloadRoute: EbookDownloadRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  DestinationsGuideSlugRoute: DestinationsGuideSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
